### ISSUE TITLE
bi-AWGN example throws error for On2/On3 algorithms

### ISSUE THREAD

**Issue by jdemel** [yp-mit/spectre#3]
Hi,

I try to run `bi-awgn/example_per.m`. Unlike the provided example `.mat` file, it does only produce one line. The one for the normal approximation algorithm.
The other algorithms throw an error. Thus, the corresponding vectors are effectively set to NaN.
The error is always as follows.
```
  MException with properties:

    identifier: 'optimlib:fmincon:InvalidSizeOfGradient'
       message: 'Provided objective gradient does not have the correct number of elements:…'
         cause: {0×1 cell}
         stack: [3×1 struct]
```
I use Matlab 2016b in case this matters. I' happy to answer further questions. And I hope you can help me out here.

**Comment by erseghe** [comment]
The problem is that the function was originally tested for Matlab 2011b. I am now fixing the bug, and soon will load an update for more recent Matlab versions.

**Comment by gdurisi** [comment]
Bug fixed
